import {describe,it,expect,beforeAll} from 'vitest';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createSolver,encode,type Solver} from '../src/engine/dds';
import {boardFromHands,deck,side,turn,legalCards,play,remainingTricks,validate} from '../src/core/cards';
import {SEATS,STRAINS,type Position,type Card} from '../src/core/types';
import {randomSource} from '../src/engine/sampling';
import {demoBoard} from '../src/core/demo';
let solver:Solver;
beforeAll(async()=>{const url=new URL('../public/dds/dds.mjs',import.meta.url).href;const {default:create}=await import(/* @vite-ignore */ url);solver=createSolver(await create({wasmBinary:readFileSync('public/dds/dds.wasm')}));},60000);
// Independent exhaustive minimax in test code: no DDS and no engine move selection.
function exhaustive(p:Position):number{const d=side(p.contract.declarer);if(!remainingTricks(p))return p.won[d];const outcomes=legalCards(p).map(c=>exhaustive(play(p,c)));return side(turn(p))===d?Math.max(...outcomes):Math.min(...outcomes);}
describe('DDS oracle comparisons',()=>{
 it('matches exhaustive minimax on 250 generated endings, including mid-trick positions',()=>{const rng=randomSource(20260905);for(let k=0;k<250;k++){const cards=deck().sort(()=>0);for(let j=cards.length-1;j>0;j--){const t=Math.floor(rng()*(j+1));[cards[t],cards[j]]=[cards[j],cards[t]];}const n=1+k%3;let p=boardFromHands(['-.-.-.-','-.-.-.-','-.-.-.-','-.-.-.-']).position;SEATS.forEach((s,i)=>p.hands[s]=cards.slice(i*n,(i+1)*n));p.contract.declarer=SEATS[k%4];p.contract.strain=STRAINS[k%5];p.leader=SEATS[(k+1)%4];for(let i=0;i<k%4;i++){const legal=legalCards(p);if(!legal.length)break;p=play(p,legal[0]);}const e=solver.solvePosition(p);expect(e.tricks,`case ${k}`).toBe(exhaustive(p));for(const m of e.moves)expect(m.tricks,`case ${k} ${m.card}`).toBe(exhaustive(play(p,m.card)));}},120000);
 it('matches 100 official full-deal tables (2000 contract positions)',()=>{const text=readFileSync('vendor/dds/hands/list100.txt','utf8');const pairs=[...text.matchAll(/PBN[^\n]*"([NESW]:[^"\n]+)"[^\n]*\nFUT[^\n]*\nTABLE ([^\n]+)/g)];expect(pairs.length).toBe(100);for(const m of pairs){const deal=m[1].slice(2).trim().split(/\s+/);const p=boardFromHands(deal).position;const expected=m[2].trim().split(/\s+/).map(Number);expect(solver.calculateTable(p).flat()).toEqual(expected);}},600000);
 it('replays 10 complete optimal lines and compares native vs WASM on every move',()=>{const text=readFileSync('vendor/dds/hands/list10.txt','utf8');const deals=[...text.matchAll(/PBN[^\n]*"N:([^"\n]+)"/g)];const positions:Position[]=[];for(let k=0;k<deals.length;k++){let p=boardFromHands(deals[k][1].split(/\s+/)).position;p.contract.strain=STRAINS[k%5];p.contract.declarer=SEATS[k%4];p.leader=SEATS[(k+1)%4];const e=solver.solvePosition(p),line=solver.generateLine(p);expect(line.steps).toHaveLength(52);for(const st of line.steps){positions.push(p);expect(legalCards(p)).toContain(st.card);p=play(p,st.card);}expect(p.won[side(p.contract.declarer)]).toBe(e.tricks);expect(validate(p)).toEqual([]);}const native=spawnSync('artifacts/native/dds-reference.exe',{input:positions.map(encode).join('\n')+'\n',encoding:'utf8',maxBuffer:10e6});expect(native.status,native.stderr).toBe(0);const results=native.stdout.trim().split('\n').map(x=>JSON.parse(x));expect(results.length).toBe(positions.length);results.forEach((r,i)=>{expect(r.code).toBe(1);const p=positions[i],n=remainingTricks(p),d=side(p.contract.declarer);for(const [s,rank,eq,v]of r.cards){const card=`${['S','H','D','C'][s]}${'23456789TJQKA'[rank-2]}`;const expected=p.won[d]+(side(turn(p))===d?v:n-v);expect(solver.solvePosition(p).moves.find(m=>m.card===card)?.tricks).toBe(expected);}});},600000);
});
